---
- hosts: Bastions_Servers
  become: false
  tasks:
    - name: Desplegando Frontend de Fondes en QA
      shell: |
        echo "Desplegando Acta Service"
        /opt/fondes/qa/scripts/deployfrontend.sh
