---
- hosts: Bastions_Servers
  become: false
  tasks:
    - name: Desplegando el servicio
      shell: |
        echo "Desplegando Reniec Service"
        /opt/fondes/qa/scripts/deployreniecservice.sh
